### ISSUE TITLE
MathExprFactory

### ISSUE THREAD

**Issue by QuanGangDeng** [bingoohuang/patchca#2]
Code line number is  29;    
private String evalExpr(String expr) {
        try {
            return "" + ((Double) engine.eval(expr)).intValue();
        } catch (ScriptException e) {
            return "error";
        }
    }

engine.eval(expr) convert to Double has occurred a ClassCastException:
java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.Double

**Comment by bingoohuang** [comment]
fix, please check the lastest commit log

**Comment by QuanGangDeng** [comment]
还有一个问题，请教一下，以下这些wordFactory我测试了一下，生成后的图片验证码，均无法实别。
//        wordFactories.add(new MathExprFactory()); // 三个单数运算
//        wordFactories.add(new MathArithmeticFactory()); // 四则运算
//        wordFactories.add(new ChineseIdiomFactory()); // 成语
//        wordFactories.add(new ChineseIdiomGuessFactory()); // 成语猜字
//        wordFactories.add(new SymbolDiffFactory()); // 符号找不同
//        wordFactories.add(new KnowledgeWordFactory()); // 地理知识
//        wordFactories.add(new RandomChineseFactory()); // 随机汉字
//        wordFactories.add(new RandomChineseJianpinFactory()); // 随机汉字简拼
//        wordFactories.add(new RandomChineseQuanpinFactory()); // 随机汉字全拼

**Comment by bingoohuang** [comment]
不知道你说的无法识别，是一个什么样的无法识别。我这边都做过测试。
